version: '3.7'
services:
  gateway:
    image: ${REGISTRY}/todoapp-gateway:${IMAGE_TAG}
    ports:
      - "${FRONTEND_PORT}:8080"
      - "${API_PORT}:8081"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/todoapp-frontend:${IMAGE_TAG}
    volumes:
      - "./frontend:/app"

  frontend-node-cli:
    image: ${REGISTRY}/todoapp-frontend-node-cli:${IMAGE_TAG}
    volumes:
      - "./frontend:/app"
    tty: true

  api:
    image: ${REGISTRY}/todoapp-api:${IMAGE_TAG}
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/todoapp-api-php-fpm:${IMAGE_TAG}
    volumes:
      - "./api:/app"

  api-php-cli:
    image: ${REGISTRY}/todoapp-api-php-cli:${IMAGE_TAG}
    volumes:
      - "./api:/app"
    depends_on:
      - api-php-fpm
    tty: true
