version: '3.7'
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - "./frontend:/app"

  frontend-node-cli:
    build:
      context: frontend/docker
      dockerfile: development/node/Dockerfile
    volumes:
      - "./frontend:/app"
    tty: true

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - "./api:/app"

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    volumes:
      - "./api:/app"
    depends_on:
      - api-php-fpm
    tty: true
