version: '3.7'
services:
  gateway:
    image: ${REGISTRY}/todoapp-gateway:${IMAGE_TAG}
    ports:
      - "${FRONTEND_PORT}:8080"
      - "${API_PORT}:8081"
      - "${MAILER_PORT}:8082"
    depends_on:
      - frontend
      - api
      - mailer

  frontend:
    image: ${REGISTRY}/todoapp-frontend:${IMAGE_TAG}
    volumes:
      - "./frontend:/app"

  frontend-node-cli:
    image: ${REGISTRY}/todoapp-frontend-node-cli:${IMAGE_TAG}
    volumes:
      - "./frontend:/app"
    tty: true

  api:
    image: ${REGISTRY}/todoapp-api:${IMAGE_TAG}
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/todoapp-api-php-fpm:${IMAGE_TAG}
    environment:
      APP_ENV: ${ENV}
      PHP_IDE_CONFIG: serverName=API
      DB_URL: pgsql://app:secret@api-postgres:5432/app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: from@email.ru
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - "./api:/app"

  api-php-cli:
    image: ${REGISTRY}/todoapp-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: ${ENV}
      DB_URL: pgsql://app:secret@api-postgres:5432/app
      MAILER_HOST: mailer
      MAILER_PORT: 1025
      MAILER_USER: app
      MAILER_PASSWORD: secret
      MAILER_ENCRYPTION: tcp
      MAILER_FROM_EMAIL: from@email.ru
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - "./api:/app"
    tty: true

  api-postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  mailer:
    image: mailhog/mailhog

volumes:
  api-postgres:
